export const VENMO_DESKTOP_AUTHORIZATION_TIMED_OUT =
  "VENMO_DESKTOP_AUTHORIZATION_TIMED_OUT";
export const VENMO_DESKTOP_AUTHORIZE = "VENMO_DESKTOP_AUTHORIZE";
export const VENMO_DESKTOP_AUTHORIZING = "VENMO_DESKTOP_AUTHORIZING";
export const VENMO_DESKTOP_CUSTOMER_CANCELED =
  "VENMO_DESKTOP_CUSTOMER_CANCELED";
export const VENMO_DESKTOP_DISPLAY_ERROR = "VENMO_DESKTOP_DISPLAY_ERROR";
export const VENMO_DESKTOP_DISPLAY_QR_CODE = "VENMO_DESKTOP_DISPLAY_QR_CODE";
export const VENMO_DESKTOP_IFRAME_READY = "VENMO_DESKTOP_IFRAME_READY";
export const VENMO_DESKTOP_CLOSED_FROM_PARENT =
  "VENMO_DESKTOP_CLOSED_FROM_PARENT";
export const VENMO_DESKTOP_REQUEST_NEW_QR_CODE =
  "VENMO_DESKTOP_REQUEST_NEW_QR_CODE";
export const VENMO_DESKTOP_UNKNOWN_ERROR = "VENMO_DESKTOP_UNKNOWN_ERROR";
export const VENMO_DESKTOP_ANALYTICS_EVENT = "VENMO_DESKTOP_ANALYTICS_EVENT";

export default {
  VENMO_DESKTOP_AUTHORIZATION_TIMED_OUT,
  VENMO_DESKTOP_AUTHORIZE,
  VENMO_DESKTOP_AUTHORIZING,
  VENMO_DESKTOP_CUSTOMER_CANCELED,
  VENMO_DESKTOP_DISPLAY_ERROR,
  VENMO_DESKTOP_DISPLAY_QR_CODE,
  VENMO_DESKTOP_IFRAME_READY,
  VENMO_DESKTOP_CLOSED_FROM_PARENT,
  VENMO_DESKTOP_REQUEST_NEW_QR_CODE,
  VENMO_DESKTOP_UNKNOWN_ERROR,
  VENMO_DESKTOP_ANALYTICS_EVENT,
};
