/**
 * Global Type Definitions for Storybook
 *
 * This file provides type definitions for global objects used in Storybook stories
 * including the Braintree SDK, PayPal SDK, and ApplePaySession.
 */

/* eslint-disable no-unused-vars */

// ============================================================================
// Braintree SDK Types
// NOTE: Most of these were generated by Claude with only some spot checking
// on their validity.
// ============================================================================

/**
 * Braintree gateway configuration returned by client.getConfiguration()
 */
interface IBraintreeConfiguration {
  authorization: string;
  authorizationType: string;
  environment: string;
  clientApiUrl: string;
  assetsUrl: string;
  configUrl: string;
  graphQL: {
    url: string;
    date: string;
    features: string[];
  };
  analytics: {
    url: string;
  };
  merchantId: string;
  venmo?: {
    accessToken: string;
    environment: string;
    merchantId?: string;
  };
  paypal?: {
    displayName?: string;
    clientId?: string;
    privacyUrl?: string;
    userAgreementUrl?: string;
    assetsUrl?: string;
    environment?: string;
    environmentNoNetwork?: boolean;
    unvettedMerchant?: boolean;
    braintreeClientId?: string;
    billingAgreementsEnabled?: boolean;
    merchantAccountId?: string;
    currencyIsoCode?: string;
  };
  paypalEnabled?: boolean;
  applePay?: {
    countryCode: string;
    currencyCode: string;
    merchantIdentifier: string;
    supportedNetworks: string[];
  };
  challenges?: string[];
  creditCards?: {
    supportedCardTypes: string[];
    supportedGateways?: Array<{
      name: string;
    }>;
  };
  threeDSecure?: {
    cardinalAuthenticationJWT?: string;
  };
  [key: string]: unknown;
}

/**
 * Braintree Client instance
 */
interface IBraintreeClient {
  getConfiguration(): { gatewayConfiguration: IBraintreeConfiguration };
  request(options: unknown): Promise<unknown>;
  teardown(): Promise<void>;
}

// ============================================================================
// Hosted Fields Types
// ============================================================================

/**
 * Field state information
 */
interface IHostedFieldState {
  container: HTMLElement;
  isFocused: boolean;
  isEmpty: boolean;
  isPotentiallyValid: boolean;
  isValid: boolean;
}

/**
 * Card type information
 */
interface ICardType {
  type: string;
  niceType: string;
  code: {
    name: string;
    size: number;
  };
  gaps: number[];
  lengths: number[];
  pattern: string | number;
}

/**
 * Hosted Fields state returned by getState()
 */
interface IHostedFieldsState {
  cards: ICardType[];
  fields: {
    number?: IHostedFieldState;
    cvv?: IHostedFieldState;
    expirationDate?: IHostedFieldState;
    expirationMonth?: IHostedFieldState;
    expirationYear?: IHostedFieldState;
    postalCode?: IHostedFieldState;
    cardholderName?: IHostedFieldState;
  };
}

/**
 * Hosted Fields tokenize payload
 */
interface IHostedFieldsTokenizePayload {
  nonce: string;
  type: string;
  details: {
    bin: string;
    cardType: string;
    expirationMonth: string;
    expirationYear: string;
    lastFour: string;
    lastTwo: string;
  };
  description: string;
  binData: {
    commercial: string;
    countryOfIssuance: string;
    debit: string;
    durbinRegulated: string;
    healthcare: string;
    issuingBank: string;
    payroll: string;
    prepaid: string;
    productId: string;
  };
}

/**
 * Hosted Fields event callback data
 */
interface IHostedFieldsEventData {
  emittedBy: string;
  fields: IHostedFieldsState["fields"];
  cards: ICardType[];
}

/**
 * Hosted Fields instance
 */
interface IHostedFieldsInstance {
  addClass(field: string, className: string): Promise<void>;
  clear(field: string): Promise<void>;
  focus(field: string): Promise<void>;
  getState(): IHostedFieldsState;
  on(
    event: string,
    callback: (data: IHostedFieldsEventData) => void
  ): IHostedFieldsInstance;
  off(
    event: string,
    callback: (data: IHostedFieldsEventData) => void
  ): IHostedFieldsInstance;
  removeAttribute(options: { field: string; attribute: string }): Promise<void>;
  removeClass(field: string, className: string): Promise<void>;
  setAttribute(options: {
    field: string;
    attribute: string;
    value: string;
  }): Promise<void>;
  setMessage(options: { field: string; message: string }): void;
  setMonthOptions(options: unknown[]): void;
  setPlaceholder(field: string, placeholder: string): Promise<void>;
  tokenize(options?: {
    vault?: boolean;
    cardholderName?: string;
    billingAddress?: unknown;
  }): Promise<IHostedFieldsTokenizePayload>;
  teardown(): Promise<void>;
}

/**
 * Hosted Fields field configuration
 */
interface IHostedFieldConfig {
  container: string | HTMLElement;
  placeholder?: string;
  type?: string;
  formatInput?: boolean;
  maskInput?: boolean | { character?: string; showLastFour?: boolean };
  select?: boolean | { options: string[] };
  maxCardLength?: number;
  minlength?: number;
  maxlength?: number;
  prefill?: string;
  rejectUnsupportedCards?: boolean;
  supportedCardBrands?: Record<string, boolean>;
}

/**
 * Hosted Fields create options
 */
interface IHostedFieldsCreateOptions {
  client?: IBraintreeClient;
  authorization?: string;
  fields: {
    number?: IHostedFieldConfig;
    cvv?: Omit<IHostedFieldConfig, "formatInput" | "maxCardLength">;
    expirationDate?: Pick<
      IHostedFieldConfig,
      "container" | "placeholder" | "type" | "select" | "prefill"
    >;
    expirationMonth?: Pick<
      IHostedFieldConfig,
      "container" | "placeholder" | "type" | "select" | "prefill"
    >;
    expirationYear?: Pick<
      IHostedFieldConfig,
      "container" | "placeholder" | "type" | "select" | "prefill"
    >;
    postalCode?: Pick<
      IHostedFieldConfig,
      | "container"
      | "placeholder"
      | "type"
      | "minlength"
      | "maxlength"
      | "prefill"
    >;
    cardholderName?: Pick<
      IHostedFieldConfig,
      | "container"
      | "placeholder"
      | "type"
      | "minlength"
      | "maxlength"
      | "prefill"
    >;
  };
  styles?: {
    input?: Record<string, string>;
    ":focus"?: Record<string, string>;
    ".valid"?: Record<string, string>;
    ".invalid"?: Record<string, string>;
    [key: string]: Record<string, string> | undefined;
  };
  preventAutofill?: boolean;
}

// ============================================================================
// Venmo Types
// ============================================================================

/**
 * Venmo tokenize payload
 */
interface IVenmoTokenizePayload {
  nonce: string;
  type: string;
  details: {
    username: string;
    payerInfo?: {
      email?: string;
      firstName?: string;
      lastName?: string;
      phoneNumber?: string;
      externalId?: string;
    };
  };
}

/**
 * Venmo instance
 */
interface IVenmoInstance {
  isBrowserSupported(): boolean;
  hasTokenizationResult(): boolean;
  tokenize(options?: {
    processResultsDelay?: number;
  }): Promise<IVenmoTokenizePayload>;
  cancelTokenization(): Promise<void>;
  teardown(): Promise<void>;
}

/**
 * Venmo create options
 */
interface IVenmoCreateOptions {
  client?: IBraintreeClient;
  authorization?: string;
  allowDesktop?: boolean;
  allowDesktopWebLogin?: boolean;
  mobileWebFallBack?: boolean;
  paymentMethodUsage?: "single_use" | "multi_use";
  profileId?: string;
  deepLinkReturnUrl?: string;
  requireManualReturn?: boolean;
  useRedirectForIOS?: boolean;
  useWebLogin?: boolean;
  collectCustomerBillingAddress?: boolean;
  collectCustomerShippingAddress?: boolean;
  displayName?: string;
  lineItems?: Array<{
    kind: "debit" | "credit";
    name: string;
    quantity: number;
    unitAmount: string;
    unitTaxAmount?: string;
    description?: string;
    productCode?: string;
    url?: string;
    imageUrl?: string;
  }>;
  subTotalAmount?: string;
  discountAmount?: string;
  taxAmount?: string;
  shippingAmount?: string;
  totalAmount?: string;
  [key: string]: unknown;
}

// ============================================================================
// Vault Manager Types
// ============================================================================

/**
 * Payment method details
 */
interface IPaymentMethod {
  nonce: string;
  type: string;
  default: boolean;
  description: string;
  details: {
    bin?: string;
    cardType?: string;
    lastFour?: string;
    lastTwo?: string;
    expirationMonth?: string;
    expirationYear?: string;
    username?: string;
    email?: string;
    payerId?: string;
    firstName?: string;
    lastName?: string;
    [key: string]: unknown;
  };
  binData?: {
    commercial: string;
    countryOfIssuance: string;
    debit: string;
    durbinRegulated: string;
    healthcare: string;
    issuingBank: string;
    payroll: string;
    prepaid: string;
    productId: string;
  };
}

/**
 * Vault Manager instance
 */
interface IVaultManagerInstance {
  fetchPaymentMethods(options?: {
    defaultFirst?: boolean;
  }): Promise<IPaymentMethod[]>;
  deletePaymentMethod(nonce: string): Promise<void>;
  teardown(): Promise<void>;
}

// ============================================================================
// PayPal Checkout Types
// ============================================================================

/**
 * PayPal Checkout create payment options
 */
interface IPayPalCheckoutCreatePaymentOptions {
  flow: "checkout" | "vault";
  amount?: string;
  currency?: string;
  intent?: "capture" | "authorize" | "order" | "tokenize";
  enableShippingAddress?: boolean;
  shippingAddressEditable?: boolean;
  shippingAddressOverride?: {
    recipientName?: string;
    line1?: string;
    line2?: string;
    city?: string;
    countryCode?: string;
    postalCode?: string;
    state?: string;
    phone?: string;
  };
  billingAgreementDescription?: string;
  displayName?: string;
  landingPageType?: "login" | "billing";
  locale?: string;
  offerCredit?: boolean;
  offerPayLater?: boolean;
  planType?: string;
  planMetadata?: unknown;
  [key: string]: unknown;
}

/**
 * PayPal Checkout tokenize payload
 */
interface IPayPalCheckoutTokenizePayload {
  nonce: string;
  type: string;
  details: {
    email?: string;
    payerId?: string;
    firstName?: string;
    lastName?: string;
    countryCode?: string;
    phone?: string;
    shippingAddress?: {
      recipientName?: string;
      line1?: string;
      line2?: string;
      city?: string;
      state?: string;
      postalCode?: string;
      countryCode?: string;
    };
    billingAddress?: {
      line1?: string;
      line2?: string;
      city?: string;
      state?: string;
      postalCode?: string;
      countryCode?: string;
    };
    [key: string]: unknown;
  };
  creditFinancingOffered?: unknown;
}

/**
 * PayPal Checkout instance
 */
interface IPayPalCheckoutInstance {
  createPayment(options: IPayPalCheckoutCreatePaymentOptions): Promise<string>;
  tokenizePayment(
    tokenizeOptions: unknown
  ): Promise<IPayPalCheckoutTokenizePayload>;
  getClientId(): Promise<string>;
  loadPayPalSDK(options?: {
    currency?: string;
    intent?: string;
    isCreditEnabled?: boolean;
    "disable-funding"?: string;
    "enable-funding"?: string;
    [key: string]: unknown;
  }): Promise<void>;
  teardown(): Promise<void>;
}

// ============================================================================
// Three D Secure Types
// ============================================================================

/**
 * 3D Secure verify options
 */
interface IThreeDSecureVerifyOptions {
  amount: string;
  nonce: string;
  bin?: string;
  email?: string;
  mobilePhoneNumber?: string;
  billingAddress?: {
    givenName?: string;
    surname?: string;
    phoneNumber?: string;
    streetAddress?: string;
    extendedAddress?: string;
    line3?: string;
    locality?: string;
    region?: string;
    postalCode?: string;
    countryCodeAlpha2?: string;
  };
  additionalInformation?: {
    workPhoneNumber?: string;
    shippingGivenName?: string;
    shippingSurname?: string;
    shippingPhone?: string;
    shippingAddress?: {
      streetAddress?: string;
      extendedAddress?: string;
      line3?: string;
      locality?: string;
      region?: string;
      postalCode?: string;
      countryCodeAlpha2?: string;
    };
    [key: string]: unknown;
  };
  challengeRequested?: boolean;
  exemptionRequested?: boolean;
  requestedExemptionType?: string;
  dataOnlyRequested?: boolean;
  cardAddChallengeRequested?: boolean;
  onLookupComplete?: (data: unknown, next: () => void) => void;
  [key: string]: unknown;
}

/**
 * 3D Secure verify payload
 */
interface IThreeDSecureVerifyPayload {
  nonce: string;
  type: string;
  liabilityShifted: boolean;
  liabilityShiftPossible: boolean;
  authenticationResponse?: string;
  lookup?: {
    threeDSecureVersion: string;
    transactionId: string;
  };
  details?: {
    bin?: string;
    cardType?: string;
    lastFour?: string;
    lastTwo?: string;
  };
  binData?: unknown;
  [key: string]: unknown;
}

/**
 * 3D Secure instance
 */
interface IThreeDSecureInstance {
  verifyCard(
    options: IThreeDSecureVerifyOptions
  ): Promise<IThreeDSecureVerifyPayload>;
  cancelVerifyCard(callback?: () => void): void;
  on(
    event: string,
    handler: (payload?: unknown, next?: () => void) => void
  ): IThreeDSecureInstance;
  off(
    event: string,
    handler: (payload?: unknown, next?: () => void) => void
  ): IThreeDSecureInstance;
  prepareLookup(options: { nonce: string; bin?: string }): Promise<string>;
  initializeChallengeWithLookupResponse(
    lookupResponse: string
  ): Promise<IThreeDSecureVerifyPayload>;
  teardown(): Promise<void>;
}

/**
 * 3D Secure create options
 */
interface IThreeDSecureCreateOptions {
  client?: IBraintreeClient;
  authorization?: string;
  version?:
    | 1
    | 2
    | "1"
    | "2"
    | "2-bootstrap3ds-modal"
    | "2-cardinal-modal"
    | "2-inline-iframe";
  cardinalSDKConfig?: unknown;
}

// ============================================================================
// Local Payment Types
// ============================================================================

/**
 * Local Payment start options
 */
interface ILocalPaymentStartOptions {
  paymentType: string;
  amount: string;
  fallback: {
    url: string;
    buttonText?: string;
  };
  currencyCode: string;
  shippingAddressRequired?: boolean;
  email?: string;
  phone?: string;
  givenName?: string;
  surname?: string;
  address?: {
    streetAddress?: string;
    extendedAddress?: string;
    locality?: string;
    postalCode?: string;
    region?: string;
    countryCode?: string;
  };
  paymentTypeCountryCode?: string;
  bic?: string;
  displayName?: string;
  windowOptions?: {
    width?: number;
    height?: number;
  };
  onPaymentStart?: (data: { paymentId: string }, start: () => void) => void;
  [key: string]: unknown;
}

/**
 * Local Payment tokenize payload
 */
interface ILocalPaymentTokenizePayload {
  nonce: string;
  type: string;
  details: {
    email?: string;
    payerId?: string;
    correlationId?: string;
    [key: string]: unknown;
  };
}

/**
 * Local Payment instance
 */
interface ILocalPaymentInstance {
  startPayment(
    options: ILocalPaymentStartOptions
  ): Promise<ILocalPaymentTokenizePayload>;
  hasTokenizationResult(): boolean;
  tokenize(): Promise<ILocalPaymentTokenizePayload>;
  focusWindow(): void;
  closeWindow(): void;
  teardown(): Promise<void>;
}

// ============================================================================
// Apple Pay Types (Simplified - avoids external namespace dependency)
// ============================================================================

/**
 * Apple Pay line item
 */
interface IApplePayLineItem {
  label: string;
  amount: string;
  type?: "final" | "pending";
}

/**
 * Apple Pay shipping method
 */
interface IApplePayShippingMethod {
  label: string;
  detail?: string;
  amount: string;
  identifier: string;
}

/**
 * Apple Pay payment contact
 */
interface IApplePayPaymentContact {
  phoneNumber?: string;
  emailAddress?: string;
  givenName?: string;
  familyName?: string;
  addressLines?: string[];
  locality?: string;
  postalCode?: string;
  administrativeArea?: string;
  country?: string;
  countryCode?: string;
}

/**
 * Apple Pay payment method
 */
interface IApplePayPaymentMethod {
  displayName?: string;
  network?: string;
  type?: "debit" | "credit" | "prepaid" | "store" | "eMoney";
  billingContact?: IApplePayPaymentContact;
}

/**
 * Apple Pay payment token
 */
interface IApplePayPaymentToken {
  paymentMethod: IApplePayPaymentMethod;
  transactionIdentifier: string;
  paymentData: Record<string, unknown>;
}

/**
 * Apple Pay payment request
 */
interface IApplePayPaymentRequest {
  countryCode: string;
  currencyCode: string;
  supportedNetworks: string[];
  merchantCapabilities: Array<
    "supports3DS" | "supportsEMV" | "supportsCredit" | "supportsDebit"
  >;
  total: IApplePayLineItem;
  lineItems?: IApplePayLineItem[];
  requiredBillingContactFields?: Array<
    "email" | "name" | "phone" | "postalAddress"
  >;
  requiredShippingContactFields?: Array<
    "email" | "name" | "phone" | "postalAddress"
  >;
  shippingMethods?: IApplePayShippingMethod[];
  shippingType?: "shipping" | "delivery" | "storePickup" | "servicePickup";
  applicationData?: string;
}

/**
 * Apple Pay tokenize payload
 */
interface IApplePayTokenizePayload {
  nonce: string;
  type: string;
  description: string;
  details: {
    cardType: string;
    cardholderName?: string;
    dpanLastTwo: string;
    rawCardType: string;
    [key: string]: unknown;
  };
  binData: {
    commercial: string;
    countryOfIssuance: string;
    debit: string;
    durbinRegulated: string;
    healthcare: string;
    issuingBank: string;
    payroll: string;
    prepaid: string;
    productId: string;
  };
  consumed: boolean;
}

/**
 * Apple Pay instance
 */
interface IApplePayInstance {
  merchantIdentifier: string;
  createPaymentRequest(
    options: Partial<IApplePayPaymentRequest>
  ): IApplePayPaymentRequest;
  performValidation(options: {
    validationURL: string;
    displayName?: string;
  }): Promise<unknown>;
  tokenize(options: {
    token: IApplePayPaymentToken;
  }): Promise<IApplePayTokenizePayload>;
  teardown(): Promise<void>;
}

// ============================================================================
// Data Collector Types
// ============================================================================

/**
 * Data Collector instance
 */
interface IDataCollectorInstance {
  deviceData: string;
  rawDeviceData: Record<string, unknown>;
  getDeviceData(): string;
  teardown(): Promise<void>;
}

// ============================================================================
// Braintree Error Type
// ============================================================================

/**
 * Braintree error structure
 */
interface IBraintreeError extends Error {
  type: "CUSTOMER" | "MERCHANT" | "NETWORK" | "INTERNAL" | "UNKNOWN";
  code: string;
  message: string;
  details?: {
    originalError?: Error | unknown;
    httpStatus?: number;
    [key: string]: unknown;
  };
}

// ============================================================================
// PayPal SDK Types
// ============================================================================

// cspell:ignore PAYLATER BANCONTACT BLIK GIROPAY MERCADOPAGO MYBANK SEPA SOFORT TRUSTLY ZIMPLER

/**
 * PayPal Buttons configuration
 */
interface IPayPalButtonsConfig {
  fundingSource?: string;
  style?: {
    layout?: "vertical" | "horizontal";
    color?: "gold" | "blue" | "silver" | "black" | "white";
    shape?: "rect" | "pill";
    label?: "paypal" | "checkout" | "buynow" | "pay" | "installment";
    height?: number;
    tagline?: boolean;
  };
  createOrder?: () => Promise<string>;
  createBillingAgreement?: () => Promise<string>;
  onApprove?: (data: {
    orderID?: string;
    payerID?: string;
    billingToken?: string;
    facilitatorAccessToken?: string;
  }) => Promise<void> | void;
  onCancel?: (data: unknown) => void;
  onError?: (err: Error) => void;
  onInit?: (
    data: unknown,
    actions: { disable: () => void; enable: () => void }
  ) => void;
  onClick?: (
    data: unknown,
    actions: { resolve: () => Promise<void>; reject: () => Promise<void> }
  ) => Promise<void> | void;
  onShippingAddressChange?: (data: unknown, actions: unknown) => Promise<void>;
  onShippingOptionsChange?: (data: unknown, actions: unknown) => Promise<void>;
  [key: string]: unknown;
}

/**
 * PayPal Buttons instance
 */
interface IPayPalButtons {
  render(container: string | HTMLElement): Promise<void>;
  close(): Promise<void>;
  isEligible(): boolean;
}

/**
 * PayPal FUNDING enum
 */
interface IPayPalFunding {
  PAYPAL: string;
  VENMO: string;
  CREDIT: string;
  CARD: string;
  PAYLATER: string;
  BANCONTACT: string;
  BLIK: string;
  EPS: string;
  GIROPAY: string;
  IDEAL: string;
  MERCADOPAGO: string;
  MYBANK: string;
  P24: string;
  SEPA: string;
  SOFORT: string;
  TRUSTLY: string;
  ZIMPLER: string;
}

/**
 * PayPal SDK
 */
interface IPayPalSDK {
  Buttons(config?: IPayPalButtonsConfig): IPayPalButtons;
  FUNDING: IPayPalFunding;
  version?: string;
}

// ============================================================================
// Global Window Extension
// ============================================================================

declare global {
  interface Window {
    braintree?: {
      client: {
        create(options: { authorization: string }): Promise<IBraintreeClient>;
        VERSION?: string;
      };
      hostedFields: {
        create(
          options: IHostedFieldsCreateOptions
        ): Promise<IHostedFieldsInstance>;
        VERSION?: string;
      };
      venmo: {
        create(options: IVenmoCreateOptions): Promise<IVenmoInstance>;
        VERSION?: string;
      };
      vaultManager: {
        create(options: {
          client?: IBraintreeClient;
          authorization?: string;
        }): Promise<IVaultManagerInstance>;
        VERSION?: string;
      };
      paypalCheckout: {
        create(options: {
          client?: IBraintreeClient;
          authorization?: string;
        }): Promise<IPayPalCheckoutInstance>;
        VERSION?: string;
      };
      threeDSecure: {
        create(
          options: IThreeDSecureCreateOptions
        ): Promise<IThreeDSecureInstance>;
        VERSION?: string;
      };
      localPayment: {
        create(options: {
          client?: IBraintreeClient;
          authorization?: string;
          merchantAccountId?: string;
        }): Promise<ILocalPaymentInstance>;
        VERSION?: string;
      };
      applePay: {
        create(options: {
          client?: IBraintreeClient;
          authorization?: string;
        }): Promise<IApplePayInstance>;
        VERSION?: string;
      };
      dataCollector: {
        create(options: {
          client?: IBraintreeClient;
          authorization?: string;
          kount?: boolean;
          paypal?: boolean;
        }): Promise<IDataCollectorInstance>;
        VERSION?: string;
      };
      VERSION?: string;
    };
    paypal?: IPayPalSDK;
    ApplePaySession?: typeof ApplePaySession;
  }

  // Global braintree reference (for convenience)
  const braintree: NonNullable<Window["braintree"]>;
  const paypal: NonNullable<Window["paypal"]>;
}

// PayPal Checkout Components types
declare module "paypal-checkout-components" {
  export interface AuthorizationResponse {
    orderID?: string;
    paymentID?: string;
    payerID?: string;
    email?: string;
    status?: string;
  }
}

export {
  IBraintreeClient,
  IBraintreeConfiguration,
  IBraintreeError,
  IHostedFieldsInstance,
  IHostedFieldsCreateOptions,
  IHostedFieldsState,
  IHostedFieldsTokenizePayload,
  IHostedFieldsEventData,
  IHostedFieldConfig,
  ICardType,
  IHostedFieldState,
  IVenmoInstance,
  IVenmoCreateOptions,
  IVenmoTokenizePayload,
  IVaultManagerInstance,
  IPaymentMethod,
  IPayPalCheckoutInstance,
  IPayPalCheckoutCreatePaymentOptions,
  IPayPalCheckoutTokenizePayload,
  IThreeDSecureInstance,
  IThreeDSecureCreateOptions,
  IThreeDSecureVerifyOptions,
  IThreeDSecureVerifyPayload,
  ILocalPaymentInstance,
  ILocalPaymentStartOptions,
  ILocalPaymentTokenizePayload,
  IApplePayInstance,
  IApplePayPaymentRequest,
  IApplePayTokenizePayload,
  IApplePayLineItem,
  IApplePayShippingMethod,
  IApplePayPaymentContact,
  IApplePayPaymentMethod,
  IApplePayPaymentToken,
  IDataCollectorInstance,
  IPayPalSDK,
  IPayPalButtons,
  IPayPalButtonsConfig,
  IPayPalFunding,
};
