#!/bin/bash

./node_modules/.bin/prettier . --ignore-unknown --check --cache

./node_modules/.bin/eslint . --cache

# Check to ensure we're either using the public NPM registry, or installing from Git
if grep '"resolved":' package-lock.json | grep -Ev '"resolved": "(https://registry\.npmjs\.org|git)'; then
	echo "-------------------------------------------------"
	echo "🥴 Found dependencies not from the public NPM registry or git"
	echo "-------------------------------------------------"

	exit 1
fi
