#!/bin/bash

# Ensure all JavaScript files staged for commit pass standard code style
FILES=$(git diff --name-only --cached --diff-filter=ACM | grep -E '(js|jsx)$' | grep -Ev '^(tasks\/|test\/)' || true)

if [ ! -z "$FILES" ]; then
	for file in $FILES; do
		if ! npx eslint "$file"; then
			echo "ESLint failed on staged file '$file'. Please fix the errors and try again."
			exit 1
		fi
	done

	# Prettify all selected files
	echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --cache --check
else
	echo -e "\033[1;31m You have no staged javascript files, skipping checks .. \033[0m"
fi
